### ISSUE TITLE
Creación de un perfil de administrativo distinto a los de gerentes o socios, con las características que se detallan en los correos.

### ISSUE THREAD

**Issue by anacid** [anacid/Tamesa-Presupuesto-P122#34]

**Comment by gregorioruiz** [comment]
La licencia sería igual que la nuestra, pero que no deje ver los resultados de los trabajos (resumen) ni la rentabilidad de las ventas.
La facturación, remesas a clientes también podriamos eliminar.
Tendría que ver los trabajos, poder abrir ordenes, hacer albaranes, pedir material, ver precios de material, fichar, ver fichajes.
El coste de los operarios también le podriamos eliminar.

Las nominas tampoco que se vean.

**Comment by gregorioruiz** [comment]
Ahora o mañana actualizamos tu programa de tamesa y me repasas esto un poco antes de instalarlo, por favor.
