### ISSUE TITLE
Nueva retencion en gastos

### ISSUE THREAD

**Issue by gregorioruiz** [anacid/Tamesa-Presupuesto-P122#51]
Añadir en la tabla estática y en variables del ejercicio la retención de prof. 3 años, al 7%

**Comment by gregorioruiz** [comment]
- [x] modificar la tabla estática
- [x] modificar ejercicio y variables
- [x] leer sus datos, modificar el gasto que puso con retención sobre la base a este y comprobar informe.

**Comment by anacid** [comment]
hecho
